services:
  apimatriz:
    build: DockerfileDebug
    ports:
      - "${PORT:-8002}:${PORT:-8002}"
    environment:
      - PORT=${PORT:-8002}
    container_name: apimatriz_${PORT:-8002}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8002}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s