services:
  apimatriz:
    build:
      context: .
      dockerfile: DockerfileDebug
    env_file:
      - ./docker/api.env
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
    volumes:
      - .:/app
      - /app/venv
    container_name: apimatriz
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s